### ISSUE TITLE
Unpinning Pinned Messages

### ISSUE THREAD

**Issue by shelbaz** [Radu-Raicea/SignalAndroid#10]
As a user, I want to unpin a pinned message.
[SP: 8]
[Priority: Medium]
[Risk: Low]

1- Expose an interface to the Activities to unpin a message (4h) -> (g-harel, Dan-Yoo, veken1199)
2- Implement a solution to delete relative info from the persistence entity (4h) -> (g-harel, Dan-Yoo, veken1199)
3- Add unpin button to top menu bar (2h) -> (erinb90, Radu-Raicea, shelbaz)
4- Link unpin to interface created (2h) -> (erinb90, Radu-Raicea, shelbaz)
Total: ?
5- Reflect the changes after unpin message is completed (3h) -> (erinb90, Radu-Raicea, shelbaz)
Total: 15h

**Comment by g-harel** [comment]
![screenshot_20180210-221155](https://user-images.githubusercontent.com/9319710/36069192-d713e444-0eb2-11e8-946c-9a6c0475ec61.jpg)

![screenshot_20180210-221219](https://user-images.githubusercontent.com/9319710/36069193-d721cfe6-0eb2-11e8-84df-a99735da2ffb.jpg)

**Comment by Radu-Raicea** [comment]
TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Unpin a Message | A pinned messaged selected by the user from conversation interface | The user will notice unpin button on the screen, Upon click, the message will be unpinned and a feedback will be displayed informing the user that the message is unpinned | PASS
Unpin a Message | A pinned message within the list of a conversation' pinned messages | The messages disappears from the list after clicking on the unpin button | PASS
Unpin a Message | A pinned messaged selected by the user from conversation interface | After unpinning the message, the message details stays unaffected | PASS
New database version | Running application | Able to see new columns added to SMS and MMS table called "pinned" | PASS
Reflect changes on database | Running application | Observe to see the changes in both SMS and MMS tables after pin and unpin operations | PASS

**Comment by Radu-Raicea** [comment]
Implementation time:
**Task 1:** 2h
**Task 2:** 3h
**Task 3:** 3h
**Task 4:** 1h
**Task 5:** 3h
Total: 12h

**Comment by jinfuchen** [comment]
Demo unpinning pinned messages. All acceptance tests pass.
1- Expose an interface to the Activities to unpin a message (done)
2- Implement a solution to delete relative info from the persistence entity (done)
3- Add unpin button to top menu bar (done)
4- Link unpin to interface created (done)
5- Reflect the changes after unpin message is completed (done)
