### ISSUE TITLE
Show emojis menu

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#102]
User Story #99

Estimated Time: 4h

**Comment by Radu-Raicea** [comment]
@shelbaz 
The keyboard should not allow you to type anything. It should also not show the message bar or send button. It should send the "add emoji reaction" request whenever you click on an emoji.

Please check mockup #100

**Comment by shelbaz** [comment]
Implementation Time: 6hr
