### ISSUE TITLE
Implement Database and Backend

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#107]
As an user, I want to be able to add emoji reactions that are sent to the recipient as well.

[SP: 13]
[Priority: high]
[Risk: med]

#108 Modify/add database tables (6h) -> (erinb90, veken1199)
#109 Implement handler (4h) -> (erinb90, veken1199)
#110 Compute the reacts associated with a message (6h) -> (erinb90, veken1199)
#111 Modify other Signal classes to introduce the feature (2h) -> (erinb90, veken1199)
#112 Write logic to intercept data messages (6h) -> (Radu-Raicea, Dan-Yoo)
#113 Send and receive Emoji reaction (8h) -> (Radu-Raicea, Dan-Yoo)

Total: 32h

Acceptance Tests :

TASK | INPUTS | EXPECTED OUTPUT | STATUS 
-- | -- | -- | -- 
Synchronized messages | Text messages | Incoming new text messages should have SHA-256 hashs | PASS
Synchronized messages | Mms messages | Incoming new Mms messages should have SHA-256 hashs | PASS
Reaction handler | any kind of messages | The system computes the returns all the associated reactions upon request in form of nested arrays | PASS
Reaction table | deleted messages |Reactions table must be updated according to prevent dangling data | PASS
Data reaction messages | sending reaction | when a reaction is sent, the tables accordingly modified | PASS
Data reaction messages | receiving reaction | when a reaction is received, the reaction table is accordingly updated | PASS

Demo Steps:
1- Connect the cellphone to the PC via USB
2- Run updated version of signal on the cellphone
3- Browse to Chrome://inspect 
4- Click on Signal instance
5- Navigate to Resources->Websql-> MessageDB->reactions

**Comment by jinfuchen** [comment]
Story description is really good.
Story points, Risk, Priority are all good.
Task breakdown is good.
Demo steps are very good.
Commit description is good.
