### ISSUE TITLE
Displaying Pinned Messages

### ISSUE THREAD

**Issue by shelbaz** [Radu-Raicea/SignalAndroid#11]
As a user, I want to display all pinned messages.

[SP: 5]
[Priority: High]
[Risk: Low]

1- Expose an interface to the Activities to load all pinned message (4h) -> (g-harel, Dan-Yoo, veken1199)
2- Add conversation options menu item to view pinned messages (3h) -> (erinb90, Radu-Raicea, shelbaz)
3- Create a new activity for the pinned message view (2h) -> (erinb90, Radu-Raicea, shelbaz)
4- Link menu item with new activity (1h) -> (erinb90, Radu-Raicea, shelbaz)
5- Implement a solution to read and filter the pinned messages from the persistence entity (5h) -> (g-harel, Dan-Yoo, veken1199)
6- Create fragments for text bubbles (5h) -> (erinb90, Radu-Raicea, shelbaz)
Total: 20h

**Comment by g-harel** [comment]
![screenshot_20180210-221226](https://user-images.githubusercontent.com/9319710/36069200-f462dbc2-0eb2-11e8-8463-aed80b896ea9.jpg)


![screenshot_20180210-221219](https://user-images.githubusercontent.com/9319710/36069181-c0148bae-0eb2-11e8-9d61-e67d80f69077.jpg)

**Comment by Radu-Raicea** [comment]
TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Display pinned messages | A 1-1 conversation that has atleast one pinned message | A new user interface that lists all the pinned messages is displayed after choosing to display all the pinned messages. Each item has the date, the username, the message, and a button to unpin the method | PASS
Display pinned messages | A 1-1 conversation that has no pinned message | A new empty user interface will be displayed after choosing to display the pinned messages, diplaying the name of the user at the top of the screen | PASS
Display pinned messages | A 1-1 conversation that has no pinned message | The user can go back to the main conversation when the back button is used | PASS
New database version | Running application | Able to see new columns added to SMS and MMS table called "pinned" | PASS
Reflect changes on database | Running application | Observe to see the changes in both SMS and MMS tables after pin and unpin operations | PASS

**Comment by Radu-Raicea** [comment]
Implementation time:
**Task 1:** 3h
**Task 2:** 2h
**Task 3:** 2h
**Task 4:** 2h
**Task 5:** 7h
**Task 6:** 15h
Total: 31h

**Comment by jinfuchen** [comment]
Demo displaying pinned messages.
All the acceptance tests pass.
