### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#114]
As a developer, I want to run tests to make sure the software works as expected.

[SP: 5]
[Priority: med]
[Risk: low]

#115 Unit Tests (5h) -> (erinb90, veken1199)
#116 UI Espresso Test (10h) -> (shelbaz, g-harel)
#117 Acceptance Tests (1h) -> (g-harel)

Total: 16h

Acceptance Tests :

TASK | INPUTS | EXPECTED OUTPUT | STATUS | 
-- | -- | -- | -- 
Unit tests | Test cases | Our new code should be covered by unit tests which verify all test cases. | PASS
Integration tests | Test cases | Our new code should be covered by UI tests which evaluate the feature at a high level by running automated tasks in the real app. | PASS
UI tests | Test cases | Automated tests should cover all major functionality of the feature | PASS

Demo Steps:
1- Run the unit tests and Espresso tests using Android Studio.

**Comment by Radu-Raicea** [comment]
Pushed to sprint 6.

**Comment by veken1199** [comment]
@erinb90 @g-harel can you add more acceptance tests ?

**Comment by erinb90** [comment]
Total implementation time: 11h
