### ISSUE TITLE
Selecting and Pinning Messages

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#12]
As a user, I want to select and pin a message.

[SP: 8]
[Priority:  High ]
[Risk:  low]

1-  Expose an interface to the Activities for pinning messages functionality (6h) -> (g-harel, Dan-Yoo, veken1199)
2-  Come up with a persistent system to store pinned messages (5h) -> (g-harel, Dan-Yoo, veken1199)
3- Add pin button to top menu bar (2h) -> (erinb90, Radu-Raicea, shelbaz)
4- Link pin button to interface created (4h) -> (erinb90, Radu-Raicea, shelbaz)
Total: 17h

**Comment by g-harel** [comment]
![screenshot_20180210-221205](https://user-images.githubusercontent.com/9319710/36069197-e7733b6e-0eb2-11e8-8d54-b20f9d45265a.jpg)

**Comment by Radu-Raicea** [comment]
TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Select and Pin a message | A text message that has not been pinned previously | A visual feedback displayed informing the user that they have pinned a message after selecting the text and clicking on the pin button | PASS
Select and Pin a message | A text message that has been pinned previously | A visual feedback displayed informing the user that they have unpinned a message after selecting the text and clicking on the pin button | PASS
Select and Pin a message | A text message that has been pinned previously | The pin button is transfromed into unpin button before the user performs the action | PASS
Select and Pin a message | A Mms message that has not been pinned previously | A visual feedback displayed informing the user that they can't pin messages of mms type | PASS
Select and Pin a message | A text message selected from a conversation | Regardless of the operation and the outcome, the message detail stays unaffected | PASS
Select and Pin a message | Individual unpinned messages | Users can pin infinite number of pin messages, but one message at a time | PASS
New database version | Running application | Able to see new columns added to SMS and MMS table called "pinned" | PASS
Reflect changes on database | Running application | Observe to see the changes in both SMS and MMS tables after pin and unpin operations | PASS

**Comment by Radu-Raicea** [comment]
Implementation time:
**Task 1:** 10h
**Task 2:** 4h
**Task 3:** 4h
**Task 4:** 6h
Total: 24h

**Comment by jinfuchen** [comment]
Demo selecting and pinning messages. All the acceptance tests pass.
1- Expose an interface to the Activities for pinning messages functionality (done)
2- Come up with a persistent system to store pinned messages (done)
3- Add pin button to top menu bar (done)
4- Link pin button to interface created (done)
