### ISSUE TITLE
Library Search

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#121]
As a developer, I want to find the library to use for compression and to document it.

[SP: 2]
[Priority: high]
[Risk: high]

#122 Finding the library (2h) -> (shelbaz)
#123 Documenting the library (2h) -> (erinb90) 

Total: 4h

Acceptance Tests :

TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Find Suitable Compression Library | Images, Video file | Compressed version of inputted file | PASS
Document the Library | Suitable library found | Article about library in our wiki | PASS

Demo Steps:
1) Go to https://github.com/Tourenathan-G5organisation/SiliCompressor
2) Add dependencies into the project
3) Use silicompressor method to intercept file being sent

**Comment by shelbaz** [comment]
Finding library : https://github.com/Tourenathan-G5organisation/SiliCompressor

**Comment by shelbaz** [comment]
#122 Implementation time: 1hr

**Comment by erinb90** [comment]
Total implementation time: 1.5h
