### ISSUE TITLE
Settings Change

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#124]
As an user, I want to have the option to use or not use compression through my settings page.

[SP: 2]
[Priority: High]
[Risk: Low]

#125 Create mockups (1h) -> (Radu-Raicea)
#126 Create UI for new setting (2h) -> (shelbaz)

Total: 3h

Acceptance Tests :

TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Draw Settings Mockup | None | A realistic settings toggle for compression | PASS
Toggle Image Compression Setting | image attachment, compression preference | valid image compression setting | PASS
Toggle Video Compression Setting | video attachment, compression preference | valid video compression setting | PASS
Toggle Gif Compression Setting | gif attachment, compression preference | valid gif compression setting | PASS

Demo Steps:
1- Open application
2- Go to Settings menu
3- Go to Chats and Media section
4- Click on Image/Video compression settings
5- Toggle image, video and/or gif compression using the checkboxes
6- Click OK to close the dialog box

**Comment by veken1199** [comment]
@shelbaz we need Screenshots

**Comment by shelbaz** [comment]
![image](https://user-images.githubusercontent.com/18130581/38773893-3b140236-4026-11e8-9219-cfad650c6b58.png)

![image](https://user-images.githubusercontent.com/18130581/38773895-50fb7f7a-4026-11e8-829c-7702909e6a0e.png)

![image](https://user-images.githubusercontent.com/18130581/38773914-9fa69876-4026-11e8-8ff0-a4aa3c868d10.png)

Implementation: 2hrs
