### ISSUE TITLE
Implementation of the compression

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#127]
As an user, I want the compression to work for images, audio, and video attachments.

[SP: 13]
[Priority: High]
[Risk: Low]

#128 Implement handler (10h) -> (Dan-Yoo, shelbaz)
#129 Modify backend to remember settings (4h) -> (Dan-Yoo)

Total: 14h

Acceptance Tests :

TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Can send compressed attachments without notiticeable interruptions | Image or Video file | No time lag | PASS
Supports sending and compressing videos, images, and gifs | Image, Video or Gif | Attachment is sent and received without errors | PASS
Compress Image | jpg file | File size smaller than non-compressed | PASS
Compress Video | mp4 file | File size smaller than non-compressed | PASS
Compress Gif | gif file | File size smaller than non-compressed | PASS

Demo Steps:
1- Open the application
2- Go to settings menu "chats and media" section
3- Toggle compression for images, videos and gifs
4- Open a conversation
5- Send an image, video or gif
6- Check that the size of the sent file is smaller than the original file

**Comment by shelbaz** [comment]
#128 Implementation time: 10 hrs

**Comment by Dan-Yoo** [comment]
#129 Implementation / Investigation time : 7h
