### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#130]
As a developer, I want to run tests to make sure the features are implemented correctly.

[SP: 3]
[Priority: Med]
[Risk: Low]

#131 Create unit tests (2h) -> (Dan-Yoo)
#132 Create acceptance tests (1h) -> (shelbaz)

Total: 3h

Acceptance Tests :

TASK | INPUTS | EXPECTED OUTPUT | STATUS 
-- | -- | -- | -- 
Unit tests | Test cases | Our new code should be covered by unit tests which verify all test cases. | PASS
Integration tests | Test cases | Our new code should be covered by UI tests which evaluate the feature at a high level by running automated tasks in the real app. | PASS
UI tests | Test cases | Automated tests should cover all major functionality of the feature | PASS

Demo Steps:
1- Run test from android studio.

**Comment by Dan-Yoo** [comment]
completed 5h

**Comment by shelbaz** [comment]
#132 Implementation time: 1hr

**Comment by g-harel** [comment]
ui tests 1.5h

**Comment by Radu-Raicea** [comment]
@g-harel @shelbaz @Dan-Yoo 
Are we okay to close this?

**Comment by g-harel** [comment]
do eet
