### ISSUE TITLE
Create acceptance tests

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#132]
User Story #130 

Estimated Time: 1h

**Comment by shelbaz** [comment]
TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Toggle Button works in Settings pane of Conversation | None | Toggle goes from On to Off , or Off to On | NOT TESTED
Attach Image or Video | Image or Video file | Compressed Image or video where file size is smaller than original | NOT TESTED
Syncronize compression toggle | compression toggle on receiver end | Compression is auto toggled on sender end | NOT TESTED

**Comment by shelbaz** [comment]
Implementation: 1hr
