### ISSUE TITLE
Emoji Reactions Improvements

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#133]
As an user, I want to have a better user experience when using the emoji reaction feature.

[SP: 13]
[Priority: High]
[Risk: Low]

#137 Duplicate emojis would merge into 1 with a number next to it (4h) -> (erinb90)
#138 Put emojis under message bubble (2h) -> (veken1199)
#139 Clicking on an emoji reacts to it (6h) -> (Radu-Raicea)
#153 Long clicking a reaction displays the sender and date of the reaction (4h) -> (erinb90)

Total: 16h

Acceptance Tests :

TASK | INPUTS | EXPECTED OUTPUT | STATUS 
-- | -- | -- | -- 
Reaction UI improvements | A message with +5 reactions | Reactions are properly displayed under the message bubble | PASS
Reaction UI improvements | A message with +5 reactions and received a new reaction | Reactions are properly displayed under message bubble, and the new reaction is properly placed on the same line if possible, otherwise it is shifted to a new line | PASS
Reaction UI improvements | A message with duplicate reactions | The number of times a reaction is received for a particular message is displayed next to that reaction icon | PASS
Reaction UI improvements | A message with a reaction reacted only by the other user | The user will react with the same reaction once they press on that reaction | PASS
Reaction UI improvements | A message with my reaction | An alert will be displayed once the reaction is pressed by the same user who reacted it indicating that the user can't react more than once to a message with the same reaction | PASS
Reaction UI improvements | A message with my reaction | Pressing and holding a reaction will display all the details related to the reaction | PASS
Reaction UI improvements | A message in group chat | Users can react to messages in group chat | PASS

Demo Steps:
1- Run updated version of signal
2- Open a conversation
3- Send a message
4- Press and hold the message bubble
5- Tab on the Emoji icon at the top navigation menu
6- Choose and click on the Emoji you want to send as a reaction to the message
7- The Emoji will appear at the bottom of the message bubble

**Comment by g-harel** [comment]
@erinb90 @veken1199 @Radu-Raicea this looks like it might be closeable since all sub-tasks are done

**Comment by Radu-Raicea** [comment]
Agreed.
