### ISSUE TITLE
Reply to messages

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#142]
As an user, I want to be able to reply and read replies on individual messages.

[SP: 8]
[Priority: High]
[Risk: Mid]

#143 Create mockups (1h) -> (Radu-Raicea)
#144 Implement UI to display the sent and received replies (1h) -> (veken1199)
#145 Extend the database to support message replies (1h) -> (veken1199)
#146 Create appropriate handlers to send and receive replies (1h) -> (veken1199)
#147 Create Unit and UI tests (3h) -> (shelbaz, erinb90)

Total: 7h

Acceptance Tests :

TASK | INPUTS | EXPECTED OUTPUT | STATUS 
-- | -- | -- | -- 
Reply to messages | A message in a conversation | Press and hold the message, the user must see reply icon at the top navigator | PASS
Reply to messages| A message in a conversation  | Press and hold the message, after clicking the reply icon, reply input replaces the regular message input bar | PASS
Reply handler | Any kind of messages | The system computes then returns all the associated replies upon request in form of nested arrays | PASS
Reply table | Deleted messages | Reply table must be updated accordingly to prevent dangling data | PASS
Data Reply messages | Sending reply | when a reply is sent, the replies tables accordingly modified | PASS
Data reply messages | Receiving reply | when a reply is received, the replies table is accordingly updated | PASS
Reply UI | Replying to a message | After typing the reply in the reply input bar and pressing "Enter" icon on the keyboard, the reply message should be displayed on the right side inside message bubble with sender name set to "Me" | PASS
Reply UI | Receiving a reply to a message | Once a reply is received, the message is displayed on the left side inside message bubble with sender name set to actual reply sender's name | PASS
Reply UI | replying/receiving replies in a group chat | Once a reply is received/sent in a group chat, the appropriate sender's name is displayed inside the message bubble | PASS

Demo Steps:
1- Open the application
2- Open a conversation
3- Send a Message
4- Press and hold that message
5- Press on the `reply` icon from the navigation on top
6- Type the reply you want
7- Send the reply by pressing `enter` from the keyboard

**Comment by veken1199** [comment]
![screenshot_2018-04-12-16-43-43](https://user-images.githubusercontent.com/15069757/38703387-1f41e354-3e71-11e8-87e3-f960a3a18917.png)
![screenshot_2018-04-12-16-43-51](https://user-images.githubusercontent.com/15069757/38703401-27b51394-3e71-11e8-8e4f-eab5b8d0cc19.png)
![screenshot_2018-04-12-16-44-10](https://user-images.githubusercontent.com/15069757/38703410-2fac24ca-3e71-11e8-86c4-9a9fb3d6daa1.png)
![screenshot_2018-04-12-16-44-17](https://user-images.githubusercontent.com/15069757/38703423-35edf07a-3e71-11e8-9ab5-c9e185b855bc.png)

**Comment by Radu-Raicea** [comment]
@erinb90 @veken1199 
Are we okay to close this?
