### ISSUE TITLE
Add indication of pinned messages in conversation

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#19]
As an user, I want to differentiate between pinned and not pinned messages in my conversations.

[SP: 8]
[Priority: Medium]
[Risk: Low]

1. #24 : Create mockups for new UI features
2. #25 : Change MessageRecord to add a Pinned indication
3. #26 : Make pin status visible in the ConversationActivity - UI
4. #27 : Refactor pin/unpin icon in ActionBar (remove database call)

Total: 15h

**Comment by erinb90** [comment]
TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Add indication of pinned messages in conversation | A pinned text message | There is a small pin indicator next to the message | PASS
Add indication of pinned messages in conversation | A pinned text message | The pin indicator disappears after the user unpins the message | PASS
Add indication of pinned messages in conversation | A non-pinned text message | There is no pin indicator next to the message | PASS
Add indication of pinned messages in conversation | A non-pinned text message | The pin indicator appears after the user pins the message | PASS

**Comment by erinb90** [comment]
Completed and merged.
Implementation time:
#24: 1h
#25: 3h
#26: 8h
#27: 1h
Total = 13h

**Comment by veken1199** [comment]
@erinb90 can you add screenshots?
