### ISSUE TITLE
Show pinned images

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#20]
As an user, I want to pin images (as opposed to just text messages).

[SP: 8]
[Priority: high]
[Risk: low]

1. #28  : Create mockups showing pinned media 
2. #29  : Unblock pinned mms method
3. #30  : Make sure attachment data is available in the record
4. #31  : Update the ui to support images 
5. #46  : Create mockups for new look
6. #50  : Block Audio/Video pinning
7. #51  : On click, display pinned images in full screen

Total: 13-24h

**Comment by Radu-Raicea** [comment]
TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Show pinned images | An image MMS message that has not been pinned previously in an 1-to-1 conversation | A visual feedback displayed informing the user that they have pinned a message after selecting the image and clicking on the pin button | PASS
Show pinned images | An image MMS message that has been pinned previously | A visual feedback displayed informing the user that they have unpinned a message after selecting the image and clicking on the pin button | PASS
Show pinned images | An image MMS message that has been pinned previously | The pin button is transfromed into unpin button before the user performs the action | PASS
Show pinned images | An image MMS message selected from a conversation | Regardless of the operation and the outcome, the message detail stays unaffected | PASS
Show pinned images | Individual unpinned messages | Users can pin infinite number of pin messages, but one message at a time | PASS
Show pinned images | Individual unpinned video type mms | Users should not be able to pin video type mms, a feed back must be displayed | PASS
Show pinned images | Individual unpinned Audio type mms | Users should not be able to pin Audio type mms, a feed back must be displayed  | PASS
Show pinned images | Pinned image in Pinned messages activity | View zoomed - full screen - version of the image once it is being clicked  | PASS

**Comment by veken1199** [comment]
![Screenshot_2018-03-02-21-22-49.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7956ee7921c8b17af2162243434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c071983fe5837a0994fcc5df04be24553b65e.png)

**Comment by veken1199** [comment]
![Screenshot_2018-03-02-21-22-49.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7956ee7921c8b17af2162243434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041f83fe5837a0994fcc5ef64ee24e50b65e.png)
![Screenshot_2018-03-02-21-33-54.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7956ee7921c8b07bf2172f43434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c071983fe5837a0994fcc5ef74fe04d52b65e.png)

**Comment by veken1199** [comment]
![Screenshot_2018-03-02-21-33-54.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7956ee7921c8b07bf2172f43434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041f83fe5837a0994fcc5ef24de9455db65e.png)

**Comment by veken1199** [comment]
![Screenshot_2018-03-02-21-33-13.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7956ee7921c8b07bf2132843434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041f83fe5837a0994fcc5ef149e54857b65e.png)

**Comment by jinfuchen** [comment]
Feature is done. Pinning image even GIF.
Story description, risk, and priority are good. 
Task breakdown is detail and really good. BTW, In the story description, for each subtask, if you can add the corresponding assignees there, that will be better.
Mockups and acceptance tests are all good.
Please add UI test for this feature.
For code quality, in class BaseHelper.java, if you catch exception, you should handle that exception.
