### ISSUE TITLE
Having the phone number show up if SMS

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#21]
As an user, I want to see the phone number of the sender of pinned messages in my pinned messages screen (as opposed to a blank space).

[SP: 0]
[Priority: High]
[Risk: Low]

No sub-tasks.
Time to complete: 2h

**Comment by g-harel** [comment]
implementation: 3h

**Comment by g-harel** [comment]
TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Having the phone number show up if SMS | A pinned message in pinned UI | Pinned sms message should display the sender's phone number | PASS

**Comment by g-harel** [comment]
![screenshot_1519873379](https://user-images.githubusercontent.com/9319710/36825037-63b190ee-1cd3-11e8-94ed-5016ff8f1cc8.png)
