### ISSUE TITLE
Improve the pinned messages view UI

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#22]
As an user, I want to have a visually pleasing UI for my pinned messages.

[SP: 5]
[Priority: High]
[Risk: Low]

1. #32 : Create mockups for new look
2. #33 : Implement view out of the mockups

Total: 8h

**Comment by g-harel** [comment]
@Radu-Raicea @erinb90 @veken1199 @Dan-Yoo @shelbaz 

Could I get some feedback on this pls

![screenshot_1519869091](https://user-images.githubusercontent.com/9319710/36823089-5dd8c6c4-1cc9-11e8-83bd-ffe9d8d1beff.png)

**Comment by erinb90** [comment]
Not sure about the right and left alignment of the messages. It kinda makes it look like a conversation when it's just a collection of messages. I think it's better to have them centered like before. 

Also not sure how I feel about the sender's name being outside the box. I think it would look better on the inside to be consistent with the regular chat (in group convos the sender name is in the box).

Colours, bubble shape and timestamp all look good.

**Comment by g-harel** [comment]
@erinb90 

About the alignment, I agree but I also think it is expected in a chat app. I am thinking of adding a separator between messages would that be better?

I specifically put it out of the box because group convos have it outside from the screenshots I found.
https://lh3.googleusercontent.com/CJAmPAeMA3CFJt-0io7N5O5J18ZcTl6twCte-zBSkYHUR6hcikFy5aJXrAsYwyUpM_8=h900
I also think it looks less cluttered, especially since this interface needs to work for 1:1 conversations where all messages have the same two senders.

**Comment by erinb90** [comment]
I just checked out WhatsApp starred message feature and the messages are shown with a separator, like this: 
https://user-images.githubusercontent.com/14361988/36823826-0b059108-1ccd-11e8-922d-d6c50fb2a1bf.png
I think something like that could be nice (just the separator, not the rest of their UI).

Also in my group convos I see the name inside the box, like here
https://user-images.githubusercontent.com/14361988/36823870-5172b8fa-1ccd-11e8-8531-77f06375ad48.png
But either way is fine, whatever you prefer.

**Comment by g-harel** [comment]
That's weird, their screenshots on the play store are wrong then.
I think I still prefer with the name outside though.

Yeah I like the what's app line.

:+1:

**Comment by veken1199** [comment]
@g-harel I like the separator idea, it looks clean, I think the name outside is different and nice "lets not make it exact clone of another app lol".

Also make sure you take in consideration that there will be pictures in there too, so hope you ui ready for different types of messages.

Also believe the list-like ui is better than chat-like ui in terms of the alianment. 

Also I dont see unpin button in the bubbles 

Overall I like it, i can go with any of the options you want

**Comment by g-harel** [comment]
You long-click to unpin

**Comment by g-harel** [comment]
total 6h

**Comment by g-harel** [comment]
TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Improve the pinned messages view UI | Pinned message UI | Pinned messages sent to and from the user should be differentiated | PASS
Improve the pinned messages view UI | Pinned message UI | Pinned messages should not look like they are part of the same conversation | PASS
Improve the pinned messages view UI | Pinned message UI | Pinned messages should display the sender's name on the message | PASS
Improve the pinned messages view UI | Pinned message UI | Pinned messages should be unpinnable with a long-click | PASS
Improve the pinned messages view UI | Pinned message UI | Pinned messages UI should match Signal's style | PASS

**Comment by g-harel** [comment]
![screenshot_1519873379](https://user-images.githubusercontent.com/9319710/36825037-63b190ee-1cd3-11e8-94ed-5016ff8f1cc8.png)

![screenshot_1519873389](https://user-images.githubusercontent.com/9319710/36825041-658b6066-1cd3-11e8-90c5-984926de71c6.png)
