### ISSUE TITLE
Remove icon/menu-item for pinned messages in group chats

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#23]
As an user, I don't want to see the pin message icon in group chats because the functionality is not implemented.

[SP: 2]
[Priority: Low]
[Risk: Medium]

No sub-tasks.
Time to complete: 3h

**Comment by veken1199** [comment]
@Radu-Raicea We need to decide how we handle this story

**Comment by veken1199** [comment]
I think we can leave the pin message, instead, we can create a story to fix the bug in the group chat pin message functionality: The app crashes when I pin my own message in a groupchat

**Comment by veken1199** [comment]
@Radu-Raicea @shelbaz do we keep this or change it to "fix the bug regarding pin messaging in group chat?? I believe they both have the same complexity,  but the later has more significance as a user.

**Comment by veken1199** [comment]
After discussing with @shelbaz  and @Radu-Raicea  we found that keeping the pin button is critical for future story #54 and we have partially implemented group chat pin, therefore after investigation, we found that keeping pin button is better solution

**Comment by veken1199** [comment]
Actual Hours : 1h

**Comment by veken1199** [comment]
TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Pin button in a group chat | group chat with 0 to many users| User selecting one message should see the pin/unpin button | PASS
Pin button in a group chat | group chat with 0 to many users| User selecting multiple messages should not see the pin/unpin button | PASS
Pin button in group chat | group chat with 0 to many users| User is able to apply the same rules of pining and unpinning in a group chat as in regular 1-1 conversation | PASS

**Comment by veken1199** [comment]
![Screenshot_2018-03-04-04-44-38.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7950ee7b24c8b77cf2112343434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041183fe5837a0984ecf59f44be84e57b65e.png)

**Comment by veken1199** [comment]
![Screenshot_2018-03-04-04-52-25.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7950ee7b24c8b67af2102e43434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041183fe5837a0984ecf59f148e24851b65e.png)
