### ISSUE TITLE
Make pin status visible in the ConversationActivity - UI

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#26]
User Story #19

Estimated Time: 3h

**Comment by veken1199** [comment]
this is almost complete, correct ?? @erinb90 , also do we need ui test ?? @g-harel

**Comment by g-harel** [comment]
~~Yeah I think we should have some tests.~~

~~@erinb90 I can take care of it or help you if you decide to make em yourself.~~

I did it

1h

**Comment by g-harel** [comment]
visibility tests

4h

**Comment by erinb90** [comment]
Implementation time: 8h
