### ISSUE TITLE
Run the application

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#3]
As a developer, I want to be able to run the application.

[SP: 1]
[Priority: High]
[Risk: Low]

**Task 1:** Install dependencies for Signal (0h)
**Task 2:** Create documentation about how to run the application (3h) -> (shelbaz)
Total: 3h

**Comment by Radu-Raicea** [comment]
Implementation time:
**Task 1:** 0h
**Task 2:** 3h
Total: 3h

**Comment by Radu-Raicea** [comment]
TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Write installation instructions (WIN, OSX) | None | Readme with formatted installation instructions | PASS
Write troubleshooting section Readme | None | Readme with formatted troubleshooting instructions | PASS

**Comment by jinfuchen** [comment]
Every member can run the App successfully.
