### ISSUE TITLE
Implement view out of the mockups

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#33]
User Story #22

Estimated Time: 6h

**Comment by veken1199** [comment]
@Radu-Raicea  did we work on this ??? @erinb90 @g-harel

**Comment by erinb90** [comment]
@veken1199 no but am planning to work on it tomorrow

**Comment by g-harel** [comment]
4a4fd685beae0ab3dfd1802dc4ac6c2449114e56

**Comment by Radu-Raicea** [comment]
@veken1199 
No we didn’t. This is for the redesign.

**Comment by g-harel** [comment]
b7fa34b21b481479a513c19ba5360afc77cfd419

**Comment by g-harel** [comment]
5h

**Comment by g-harel** [comment]
![screenshot_1519873379](https://user-images.githubusercontent.com/9319710/36825037-63b190ee-1cd3-11e8-94ed-5016ff8f1cc8.png)

![screenshot_1519873389](https://user-images.githubusercontent.com/9319710/36825041-658b6066-1cd3-11e8-90c5-984926de71c6.png)
