### ISSUE TITLE
Setting nicknames in a conversation

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#34]
As an user, I want to be able to set another user’s nickname in a conversation or a chat.

[SP: 8]
[Priority: High]
[Risk: Medium]

1. #37 : Create Mockups 
2. #38 : Provide a public interface (backend) to set nicknames
3. #39 : Implement UI components to allow user to set nickname in conversation settings

Total: 7h

**Comment by veken1199** [comment]
![Screenshot_2018-03-04-03-14-19.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7950ee7b23c8b27cf2132243434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041f83fe5837a0984ec95bf14fe8455db65e.png)

**Comment by veken1199** [comment]
![Screenshot_2018-03-04-03-14-44.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7950ee7b23c8b27cf2162f43434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041183fe5837a0984ec95df249e44450b65e.png)

**Comment by veken1199** [comment]
![Screenshot_2018-03-04-03-14-49.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7950ee7b23c8b27cf2162243434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041f83fe5837a0984ec95ef34ee54954b65e.png)

**Comment by veken1199** [comment]
@shelbaz user acceptance

**Comment by shelbaz** [comment]
TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Set nickname from a contact in conversation | A nickname as a string | All instances of the users name is replaced with the nickname | PASS
Reset nickname from a contact in conversation | Nothing | Nickname has been erased and name is reset back to contact name | PASS
Set nickname for a regular number in conversation | A nickname as a string | All instances of the users name is replaced with the nickname | PASS
Reset nickname for a regular number in conversation | Nothing | Nickname has been erased and name is reset back to contact phone number | PASS
Nickname persists even after app closes and reopens | Nothing | All instances of the users name is replaced with the nickname | PASS
Set chat group nickname | group chat | User changes/adds a nickname to a group chat | PASS
Unset chat group nickname | group chat with group chat nickname  | User unsets the group chat nickname and the original group chat name will be restored | PASS

**Comment by jinfuchen** [comment]
Feature setting nickname is done.
Story description is good.
Mockups and acceptance tests are good.
Please add UI tests for this feature.
