### ISSUE TITLE
Removing a nickname

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#36]
As an user, I want to be able to remove another user’s nickname.

[SP: 2]
[Priority: High]
[Risk: Low]

1. #41 : Provide a public interface to unset the nickname
2. #42 : Implement UI components to allow user to unset nickname in conversation settings

Total: 3h

**Comment by Dan-Yoo** [comment]
TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Reset nickname click when recipient has no nickname| recipient with no nickname | No change in the displayed name | PASS
Reset nickname click when recipient has nickname and no name | recipient with nickname | Nickname is set to null and address is shown instead | PASS
Reset nickname click when recipient has nickname and name | recipient with nickname and name | Nickname is set to null and name is shown instead | PASS
