### ISSUE TITLE
Provide a public interface (backend) to set nicknames

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#38]
User Story #34

Estimated Time: 4h

**Comment by veken1199** [comment]
I believe the best approach for this is:
1- introduce new database update to include "nickname" attribute in "identities table" 
2- create new handler to set the nicknames, this will help us to easily write unit tests

**Comment by veken1199** [comment]
@Dan-Yoo  @shelbaz interesting fact, Signal stores all your contacts in table called "recipient_preferences". It gets accessed through RecipientDatabase class, there is method that returns all the info related to a recipient to "getIndividualRecipientDetails" in RecipientProvider class in a form of RecipientDetails object

**Comment by veken1199** [comment]
Actual  time : 5h
