### ISSUE TITLE
Implement UI components to allow user to set nickname in conversation settings

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#39]
User Story #34

Estimated Time: 2h

**Comment by Dan-Yoo** [comment]
i created this ui in my nickname-ui branch

**Comment by veken1199** [comment]
@Dan-Yoo can you show a screen shot of the ui

**Comment by veken1199** [comment]
@Dan-Yoo can you show a screenshot

**Comment by shelbaz** [comment]
<img width="249" alt="screen shot 2018-03-04 at 3 37 20 pm" src="https://user-images.githubusercontent.com/18130581/36950283-f987e12c-1fc1-11e8-84ef-c3135adfa057.png">

Implementation : 2hr
UI Tests : 4 hrs
