### ISSUE TITLE
Make the architectural diagrams

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#4]
As a developer, I want to view architectural diagrams to understand how the application works.

[SP: 13]
[Priority: Medium]
[Risk: High]

**Task 1:** Verify with TA if the diagrams can have smaller scope due to size of app (0h)
**Task 2:** Create overall layers diagram (21h) -> (g-harel, Dan-Yoo, veken1199)
**Task 3:** Component Diagram using a tool (18h) -> (g-harel, veken1199, erinb90)
**Task 4:** Create mockups (5h) -> (Dan-Yoo)
**Task 5:** Create the task diagram (2h) -> (erinb90, Radu-Raicea)
Total: 46h

**Comment by erinb90** [comment]
Task Diagram for Sprint 1 completed
Done by myself and @Radu-Raicea 
![task diagram](https://user-images.githubusercontent.com/14361988/35415667-6cf587e0-01f4-11e8-90e8-5b766eda5c8b.png)

**Comment by erinb90** [comment]
Task 3 completed by myself, @g-harel and @veken1199 
Total implementation time: 21h

**Comment by veken1199** [comment]
Task 2 completed by myself, @Dan-Yoo  and @g-harel 
Total implementation time: 14h

**Comment by veken1199** [comment]
Task 4 completed by @Dan-Yoo 
Total implementation time:  4h

**Comment by veken1199** [comment]
Application Layered Architecture Diagram for Sprint 1 Completed:
Done by myself @g-harel  and @Dan-Yoo  ![LayerDiagram.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46c495832690a7a08eeead42a91fbcd6395428792c07b7692ac7b629ea1b2f020b561da448500e44fcf98f2aa5b66a228e5819f1c32f0e2a92624cf5f2d75dad0ba821824584b3bd8d4dc1ea3d2de28389492c53.png)

**Comment by veken1199** [comment]
Component Diagram for Sprint 1 is completed
Done by myself, @g-harel and @erinb90 
![Component Diagram.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46cb9b97338d8dac81fdff67ad5cf786284b653f6b14b1247a80e03cfd1839540e5a47a8120c5617f4f0817aa6b63c768b5f0bbb83695b66da2f53fde6d640e258f075c95d8fa4bd8c46c1ed3c22e68a8d483e1d001a88ed10.png)

**Comment by veken1199** [comment]
Application Mockups for Sprint 1 is completed:
Done by @Dan-Yoo
![screenshot-mockup.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46fb978826878dba87e6ab0ea952f39f3c56653f6b14b1247a80e03cfd1839540e5a47a8120c5617f4f0817aa6b63c768b5f0bbb83695b66da2f53fde6d640e258f075c95d8fa4bd8246c1ed3c22e68a8d463f1d071a8ced10.png)

**Comment by Radu-Raicea** [comment]
TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Create overall layers diagram | Source Code | Layer diagram capturing the presentation, business, persistence, and shared services layers | PASS
Component Diagram | Souce Code | Well defined application components, identified by User interface functionality and business logic | PASS
Create mockups | Running Application | Visual representation of application's user interface | PASS
Create the task diagram | Deadlines, Start dates, and number of sprints per release | Task diagram showing the order and progression of releases, sprints and tasks | PASS

**Comment by jinfuchen** [comment]
Extract overall layer diagram, component diagram and mockups by manually.
The three types of the diagram can represent the architecture of Signal.
