### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#5]
As a developer, I want to run CI tests to verify the correctness of my code.

[SP: 3]
[Priority: Low]
[Risk: Medium]

**Task 1:** Setup Travis CI (1h) -> (Radu-Raicea)
**Task 2:** Implement an automated test pipeline that is triggered after every commit/push (10h) -> (shelbaz, Radu-Raicea)
Total: 11h

**Comment by Radu-Raicea** [comment]
Implementation time:
**Task 1:** 1h
**Task 2:** 9h
Total: 10h

**Comment by Radu-Raicea** [comment]
TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Create travis automatic builds on commits | Pull request to merge commit | Travis build, with build passing successfully | PASS
Travis autorun all tests on commits | Pull request to merge commit | Travis build, with build and all tests passing successfully | PASS

**Comment by jinfuchen** [comment]
Travis CI setup is done.
