### ISSUE TITLE
All message type pin functionality support

### ISSUE THREAD

**Issue by veken1199** [Radu-Raicea/SignalAndroid#54]
As a user, I want to be able to pin all type of messages in regular conversations, and group conversations.

[SP: 3]
[Priority: High]
[Risk: Low]

#80 : Create Mockups
#58 : Allow pinning/unpinning any type of messages (2h) -> (veken1199)
#62 : Allow displaying any type pinned messages in pinned messages activity (1h) -> (veken1199)
#55 : Fix the bug : The app breaks when I pin my own text message in a group chat (1h) -> (veken1199)
#63: Allow fully functional pin feature in group chat (1h) -> (veken1199)
#85: UI Tests  (5h) -> (veken1199, g-harel )

Total: 10h

Acceptance tests: 

TASK | INPUTS | EXPECTED OUTPUT | STATUS | 
-- | -- | -- | -- 
Pinning my own text message in group chat| The user sends a text message in a group chat | The user can pin that message in the group chat and is able to see it in the pinned messages activity | PASS
Pinning  and unpinning video in a conversation | received or sent video file in a conversation| The user is able to pin and unpin the video file and then retrieve it in the pinned messages activity| PASS
Pinning and unpinning audio in a conversation | received or sent audio file in a conversation | The user is able to pin and unpin the audio file and then retrieve it in the pinned messages activity| PASS
Pinning and  unpinning documents in a conversation | received or sent document file in a conversation | The user is able to pin and unpin the document file and then retrieve it in the pinned messages activity| PASS
Pinning and  unpinning documents in a group chat | received or sent document file in a group chat | The user is able to pin and unpin the document file and then retrieve it in the pinned messages activity| PASS
Pinning and unpinning audio in a group chat | received or sent audio file in a group chat | The user is able to pin and unpin the audio file and then retrieve it in the pinned messages activity| PASS
Pinning  and unpinning video in a group chat | received or sent video file in a group chat | The user is able to pin and unpin the video file and then retrieve it in the pinned messages activity| PASS
Loading the content of an audio file in pinned messages activity | A pinned received or sent audio file in a conversation or group chat | The user is able to load and listen the  pinned audio file in pinned messages activity when they click on it | PASS
Loading the content of a video file in pinned messages activity | A pinned received or sent video file in a conversation or group chat | The user is able to load and play the pinned video file in pinned messages activity when they click on it | PASS
Loading the content of a document file in pinned messages activity | A pinned received or sent document file in a conversation or group chat | The user is able to load and view the pinned document file in pinned message activity when they click on it | PASS

**Comment by veken1199** [comment]
[Uploading Screenshot_2018-03-17-22-25-42.png...]
[Uploading Screenshot_2018-03-17-22-25-22.png...]
[Uploading Screenshot_2018-03-17-22-25-18.png...]
[Uploading Screenshot_2018-03-17-22-25-07.png...]
[Uploading Screenshot_2018-03-17-22-24-58.png...]
[Uploading Screenshot_2018-03-17-22-24-52.png...]

**Comment by veken1199** [comment]
![Screenshot_2018-03-17-22-25-42.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7853ee7922c8b17df2162943434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041f83fe5837a19a4fc95cfe4fe94950b65e.png)
![Screenshot_2018-03-17-22-25-22.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7853ee7922c8b17df2102943434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041083fe5837a19a4fc95df64be84855b65e.png)
![Screenshot_2018-03-17-22-25-18.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7853ee7922c8b17df2132343434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041f83fe5837a19a4fc95df74be54b50b65e.png)
![Screenshot_2018-03-17-22-25-07.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7853ee7922c8b17df2122c43434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041f83fe5837a19a4fc95df74be44f50b65e.png)
![Screenshot_2018-03-17-22-24-58.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7853ee7922c8b17cf2172343434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c071883fe5837a19a4fc95df74be44e52b65e.png)
![Screenshot_2018-03-17-22-24-52.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7853ee7922c8b17cf2172943434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041f83fe5837a19a4fc95df74be74953b65e.png)

**Comment by jinfuchen** [comment]
Feature of pinning all types of messages is done.
Story description is good.
Task breakdown is good. 
Mockups for this feature is good.
Acceptance tests are good.
Unit tests are good.
