### ISSUE TITLE
UI for search conversation

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#66]
As a user, I want to interact with an UI to search for messages in my conversations.

[SP: 20]
[Priority: High]
[Risk: Medium]

#67 Create mockups (2h) -> (Radu-Raicea)
#68 Add search bar UI (Display search bar UI and return to previous UI) (6h) -> (erinb90, shelbaz)
#69 Add method to highlight parts of messages (3h) -> (g-harel)
#70 Display result messages (6h) -> (Dan-Yoo, Radu-Raicea)
#71 Add scroll between messages (3h) -> (g-harel)
#72 Create espresso tests (delayed to Sprint 5) (7h) -> (shelbaz, g-harel)

Total: 27h

Acceptance tests

TASK | INPUTS | EXPECTED OUTPUT | STATUS | 
-- | -- | -- | -- 
Search UI | 1-1 Conversation with search mode deactivated  | When the user clicks "Search conversation", an empty search bar is displayed | PASSED
Search UI | 1-1 Conversation with search mode activated  | User can deactivate the search mode and go back to the original conversation view by pressing the "back" button | PASSED
Search UI | Message position | When messages matched the search term, the Recycler View should scroll to the provided position |PASSED
Search UI | Searched string | The Conversation item should highlight matching substrings | PASSED
Search UI | Matched messages | The Recycler view should move the view to the next message in the conversation that matches the search term when "next button" is clicked | PASSED
Search UI | Matched messages | The Recycler view should move up "older messages" the view to the previous message in the conversation that matches the search term when "up button" is clicked | PASSED
Search UI | Matched messages | The Recycler view should move the view to the next message in the conversation that matches the search term when "down button" is clicked | PASSED
Search UI | Matched messages | A toast is displayed when the user clicks on the "up button" when oldest messages containing the search term is reached |  PASSED
Search UI | Matched messages | A toast is displayed when the user clicks on the "down button" when newest messages containing the search term is reached | PASSED

**Comment by veken1199** [comment]
![Screenshot_2018-03-17-23-55-25.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7853ee7923c8b67df2102e43434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041f83fe5837a19a4fcd5df04ae44f52b65e.png)
![Screenshot_2018-03-17-23-51-13.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7853ee7923c8b679f2132843434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c071883fe5837a19a4fcd5df04ae44554b65e.png)
![Screenshot_2018-03-17-23-50-55.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7853ee7923c8b678f2172e43434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c071883fe5837a19a4fcd5df04ae74c51b65e.png)
![Screenshot_2018-03-17-23-50-46.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7853ee7923c8b678f2162d43434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041f83fe5837a19a4fcd5df04ae44455b65e.png)
![Screenshot_2018-03-17-23-50-38.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7853ee7923c8b678f2112343434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c041f83fe5837a19a4fcd5df04ae74c56b65e.png)
![Screenshot_2018-03-17-23-50-27.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7853ee7923c8b678f2102c43434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c071983fe5837a19a4fcd5df04ae44f56b65e.png)
![Screenshot_2018-03-17-23-50-24.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bb8e15f14900011cc08a5/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7853ee7923c8b678f2102f43434d0eee1e020a17b8eb8339a3e739798e0f5fe48265567c973d11acbe831cbf57e8248f5d99a4fedb1294b7607caddecd5d340c071883fe5837a19a4fcd5df04ae44551b65e.png)
