### ISSUE TITLE
Backend for search

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#73]
As a user, I want the search functionality to return the correct message results for my search.

[SP: 20]
[Priority: High]
[Risk: High]

#74 Create a separate class to store messages ready to be searched (3h) -> (erinb90, veken1199)
#75 Create method to find messages that match search string (2h) -> (erinb90)
#76 Create method to replace message in the RecyclerView (6h) -> (Dan-Yoo, Radu-Raicea)
#77 Create method to reset search state (2h) -> (Dan-Yoo)
#78 Create unit tests (4h) -> (erinb90, veken1199)

Total: 17h

Acceptance Tests :

TASK | INPUTS | EXPECTED OUTPUT | STATUS | 
-- | -- | -- | -- 
Search Message | Keyword not contained in any message | When the user searches for a keyword not contained in any message, the System should behave accordingly | PASSED
Search Message | Conversation with at least 1 message | After search is completed, none of the existed original messages is modified or deleted | PASSED
 Search Message | Conversation with at least 1 message | After search is completed, the order of the messages in the conversation should be preserved | PASSED
Search Message | Conversation in search mode and with one or more messages | The system should indicate whether the new messages contain the search keyword | PASSED
Search Message | Conversation with at least 2 messages and in search mode | The system should handle changes and preserve the original ordered positions of the messages when a message or more are deleted | PASSED

**Comment by Radu-Raicea** [comment]
@Dan-Yoo @erinb90 

TODO: Create the class diagrams for the 4 classes used in the search (ConversationActivity, ConversationFragment, ConversationAdapter, SearchHandler).

I can do it with the Eclipse plugin if you guys want (ObjectAid).

**Comment by Radu-Raicea** [comment]
@erinb90 Not sure if your thumbs up means you'll do it or want me to do it

**Comment by erinb90** [comment]
@Radu-Raicea I'll try it with the Android Studio tool

edit: never mind, that one sucks, I'll use the Eclipse one

**Comment by jinfuchen** [comment]
Feature searching conversation is done.
Please update risk and priority in the story description.
Task breakdown is good. There is balanced work for each team member.
Mockups for this feature is good.
Acceptance tests: there is one case that you still did not test. Please test and update the Status in the acceptance tests table.
Unit tests are good. There are successful tests and fail tests too.
