### ISSUE TITLE
Investigate how to synchronize

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#98]
As a developer, I want messages to share an identity across devices.

[SP: 1]
[Priority: high]
[Risk: high]

Total: 1h

Acceptance Tests :

TASK | INPUTS | EXPECTED OUTPUT | STATUS | 
-- | -- | -- | -- 
Synchronize messages | Received messages | Each message should have a unique identity shared across devices. | PASS
Synchronize messages | Old message | Each old message should have a unique identity shared across devices. | PASS

**Comment by Radu-Raicea** [comment]
@veken1199 @Dan-Yoo @g-harel 
Could any of you fill in the description please? Not sure what this is.

**Comment by g-harel** [comment]
@Radu-Raicea 

gotta have all the people in the chat agree on message ids

messages have their own id locally, but we also need some kind of shared id if we wanna add reactions to specific messages. like remote foreign key

**Comment by g-harel** [comment]
I suggest hashing the [sendTime + senderNumber] into a 64 char string. This could be applied retroactively to past messages aswell.

**Comment by veken1199** [comment]
Implementation: 1h
