### ISSUE TITLE
Make UI changes

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#99]
As an user, I want to interact with the UI to react to a message using an emoji.

[SP: 8]
[Priority: high]
[Risk: med]

#100 Create mockups (1h) -> (Radu-Raicea)
#101 Create UI element on hold press (3h) -> (Radu-Raicea)
#102 Show emojis menu (4h) -> (shelbaz)
#103 Show received reactions (4h) -> (Dan-Yoo)

Total: 12h

Acceptance Tests :

TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Show Emoji reaction menu | A one-to-one conversationActivity screen, long hold on message, click emoji icon | The emoji keyboard comes up | PASS
Show Emoji reaction menu | A group messaging conversationActivity screen,  long hold on message, click emoji icon | The emoji keyboard comes up | PASS
Click emoji reaction | Inside 1-1 conversation screen | Emoji reaction is added to message | PASS
Click emoji reaction | Inside group message conversation screen | Emoji reaction is added to message | PASS

Demo Steps:
1- Run updated version of signal 
2- Open a conversation 
3- Send a message
4- Press and hold the message bubble
5- Tab on the Emoji icon at the top navigation menu
6- Choose and click on the Emoji you want to send as a reaction to the message
7- The Emoji will appear at the bottom of the message bubble

**Comment by shelbaz** [comment]
Implementation Time: 6hr

**Comment by veken1199** [comment]
![screenshot_2018-04-04-16-22-02](https://user-images.githubusercontent.com/15069757/38332798-cf456530-3824-11e8-8caf-8b1a7bd9bb5f.png)
![screenshot_2018-04-04-16-22-15](https://user-images.githubusercontent.com/15069757/38332801-d1e6efac-3824-11e8-8e0a-f1511d66b4c9.png)
![screenshot_2018-04-04-16-22-26](https://user-images.githubusercontent.com/15069757/38332809-d684f3ba-3824-11e8-87de-35b5def66ad9.png)

**Comment by jinfuchen** [comment]
UI is good. 
Mockup and acceptance tests are very good.
